// @ts-expect-error Generated by the Cloudflare adapter during build.
import app from './.svelte-kit/cloudflare/_worker.js';
import {
	deliverNotifications,
	type NotificationEnvironment
} from './src/lib/server/booking-notifications';
export default {
	fetch(request: Request, env: NotificationEnvironment, context: ExecutionContext) {
		if (new URL(request.url).pathname.startsWith('/admin'))
			return new Response('Not Found', { status: 404 });
		return app.fetch(request, env, context);
	},
	scheduled(_event: ScheduledController, env: NotificationEnvironment, context: ExecutionContext) {
		context.waitUntil(deliverNotifications(env));
	}
};
