// @ts-expect-error Generated by the Cloudflare adapter during build.
import app from './.svelte-kit/cloudflare/_worker.js';
import {
	deliverNotifications,
	type NotificationEnvironment
} from './src/lib/server/booking-notifications';
export default {
	fetch(request: Request, env: NotificationEnvironment, context: ExecutionContext) {
		if (new URL(request.url).pathname.startsWith('/admin'))
			return new Response('Not Found', {
				status: 404,
				headers: {
					'Content-Type': 'text/plain; charset=utf-8',
					'X-Content-Type-Options': 'nosniff',
					'X-Frame-Options': 'DENY',
					'Content-Security-Policy': "default-src 'none'; frame-ancestors 'none'",
					'Cache-Control': 'no-store'
				}
			});
		return app.fetch(request, env, context);
	},
	scheduled(_event: ScheduledController, env: NotificationEnvironment, context: ExecutionContext) {
		context.waitUntil(deliverNotifications(env));
	}
};
